import { CurrentRideProvider } from '@/components/providers/current-ride-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { UserProvider } from '@/components/providers/user-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { QueryProvider } from '../components/providers/query-provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <QueryProvider>
            <UserProvider>
              <CurrentRideProvider>{children}</CurrentRideProvider>
            </UserProvider>
          </QueryProvider>
        </SocketProvider>
      </body>
      <Script
        async
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places&callback=GMAPSSCRIPT`}
      />
    </html>
  )
}
